import { describe, expect, it, vi } from "vitest";
import { createDatabase, createProject, getProjectForUser, upsertUser } from "../server/db";
import { assertSpineTextAllowed, coverArtPrompt, createCoverPlanVersion, getLatestCoverPlan, importCoverTemplate, invalidateCoverPlansForInteriorChange, makeInteriorFingerprint, validateCoverPlacement } from "../server/cover-desk";
import type { PrivateStorage } from "../server/storage";

const owner = { id: "cover-owner", name: "Cover Owner", email: "cover@example.com" };
function setup() { const db = createDatabase(":memory:"); upsertUser(db, owner); const project = createProject(db, owner.id, { id: "cover-project", name: "Cover Book", brief: "A cover test" }); return { db, project }; }
function storage() { return { put: vi.fn(async (key: string) => ({ key })), delete: vi.fn(async () => undefined), createAccessUrl: vi.fn(async (key: string) => `/private/${key}`) } as PrivateStorage; }
function plan(pageCount: number, templateImportId?: string) { return { binding: "paperback" as const, trimWidthInches: 8.5, trimHeightInches: 8.5, finalInteriorPageCount: pageCount, paperSelection: "white", inkSelection: "black_ink", readingDirection: "ltr" as const, title: "The Little Gate", subtitle: "", author: "A. Author", imprint: "", backCoverCopy: "A small story.", barcodeDecision: "amazon_placed" as const, spineTextPermitted: false, templateImportId, inputsConfirmed: Boolean(templateImportId) }; }

async function importTemplateFixture(db: ReturnType<typeof createDatabase>, projectId: string) { const project = getProjectForUser(db, owner.id, projectId)!; return importCoverTemplate(db, storage(), owner.id, projectId, { sourceUrl: "https://kdp.amazon.com/cover-calculator", retrievedAt: new Date().toISOString(), calculatorInputs: { pageCount: 24, trim: "8.5x8.5", paper: "white", ink: "black_ink" }, guideBytes: Buffer.from("template-guide"), guideMimeType: "application/pdf", fullCoverWidthInches: 17.25, fullCoverHeightInches: 8.75, bounds: { front: {}, back: {}, spine: {} }, safeZones: { front: {}, back: {}, spine: {} }, bleedZones: { all: 0.125 }, barcodeMargin: { fromSpine: 0.25, fromTrim: 0.25 }, spineSafeZone: { sideInset: 0.0625 }, interiorFingerprint: makeInteriorFingerprint(project, 24) }); }

describe("Cover Desk", () => {
  it("gates spine text below the KDP paperback threshold", () => { expect(() => assertSpineTextAllowed(78, true)).toThrow(/79/); expect(() => assertSpineTextAllowed(79, true)).not.toThrow(); });
  it("requires no readable text, barcode, or spine lettering in art prompts", () => { const prompt = coverArtPrompt("front", "A warm garden scene"); expect(prompt).toMatch(/readable cover text/i); expect(prompt).toMatch(/barcode/i); expect(prompt).toMatch(/spine lettering/i); });
  it("imports a current template, versions the plan, and invalidates it when page count changes", async () => { const { db, project } = setup(); const template = await importTemplateFixture(db, project.id); const saved = createCoverPlanVersion(db, owner.id, project.id, plan(24, template.id)); expect(saved.version).toBe(1); expect(saved.inputsConfirmed).toBe(true); const invalidated = invalidateCoverPlansForInteriorChange(db, owner.id, project.id, makeInteriorFingerprint(project, 25)); expect(invalidated).toBe(1); expect(getLatestCoverPlan(db, owner.id, project.id)?.status).toBe("needs_template_refresh"); expect((db.prepare("SELECT status FROM cover_template_imports WHERE id = ?").get(template.id) as any).status).toBe("invalidated"); });
  it("rejects a confirmed plan linked to a stale template", async () => { const { db, project } = setup(); const template = await importTemplateFixture(db, project.id); expect(() => createCoverPlanVersion(db, owner.id, project.id, plan(25, template.id))).toThrow(/stale/i); });
  it("warns for safe-zone and barcode exclusion violations", () => { const warnings = validateCoverPlacement([{ surface: "front", kind: "text", x: 0, y: 0, width: 2, height: 1 }, { surface: "back", kind: "art", x: 1, y: 1, width: 2, height: 2 }, { surface: "spine", kind: "text", x: 0, y: 0, width: 0.5, height: 1 }], { safeZones: { front: { x: 0.25, y: 0.25, width: 8, height: 8 }, back: { x: 0.25, y: 0.25, width: 8, height: 8 }, spine: { x: 0.0625, y: 0.0625, width: 0.125, height: 8.3 } }, barcodeZone: { x: 0.5, y: 0.5, width: 2, height: 1.2 } }); expect(warnings.map((warning) => warning.code)).toEqual(expect.arrayContaining(["outside_safe_zone", "barcode_exclusion_overlap", "spine_clearance"])); });
});
