import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { createDatabase, createProject, upsertUser } from "../server/db";
import { createBookBrief, createPagePlan, ensureCoverArtPage, listPagePlans } from "../server/db-studio";
import { composePromptFromSavedProject, NO_TEXT_RULE_MARKER } from "../server/prompt-composer";
import { createFalGenerationService, type GenerationAdapter } from "../server/fal-generation";
import { drainQueueOnce } from "../server/generation-queue";
import { createAppRouter } from "../server/routers";
import { falModelRegistry } from "../server/fal-models";
import type { PrivateStorage } from "../server/storage";

const owner = { id: "cover-art-owner", name: "Owner", email: "owner@example.com" };
const stranger = { id: "cover-art-stranger", name: "Stranger", email: "stranger@example.com" };
const pngBytes = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");

function makeStorage(): PrivateStorage {
  const objects = new Map<string, Uint8Array>();
  return {
    put: vi.fn(async (key, bytes) => { objects.set(key, bytes); return { key }; }),
    delete: vi.fn(async (key) => { objects.delete(key); }),
    createAccessUrl: vi.fn(async (key) => `/private/${key}`),
  };
}

function makeAdapter() {
  const adapter: GenerationAdapter = {
    submit: vi.fn(async () => ({ requestId: "cover-req", gatewayRequestId: "cover-req", responseUrl: null, statusUrl: null, cancelUrl: null })),
    status: vi.fn(async (_e, requestId) => ({ status: "COMPLETED" as const, requestId })),
    result: vi.fn(async () => ({ images: [{ url: "https://fal.media/files/cover.png", content_type: "image/png", width: 1, height: 1 }] })),
    cancel: vi.fn(async () => "cancellation_requested" as const),
    downloadImage: vi.fn(async () => ({ bytes: pngBytes, contentType: "image/png" })),
  };
  return adapter;
}

function fixture(interiorArtStyle: "full_color" | "coloring_line_art" = "full_color") {
  const db = createDatabase(":memory:");
  upsertUser(db, owner);
  upsertUser(db, stranger);
  const project = createProject(db, owner.id, { id: "cover-art-project", name: "Moon Garden", brief: "A picture book." });
  db.prepare("UPDATE book_projects SET interior_art_style = ? WHERE user_id = ? AND id = ?").run(interiorArtStyle, owner.id, project.id);
  createBookBrief(db, owner.id, {
    id: "cover-art-brief", projectId: project.id, briefText: "A kitten learns to ask for help.",
    bookType: "picture_book", audience: "preschool children", visualStyleAnchors: "Warm watercolor.",
    characterBible: "Milo is a small orange kitten with a blue collar.", negativePrompt: "No logos.",
    characters: [{ name: "Milo", description: "A small orange kitten with a blue collar." }],
  });
  createPagePlan(db, owner.id, { id: "cover-art-page-1", projectId: project.id, pageNumber: 1, sceneDirection: "Milo sits by the door.", pageText: "MILO WAITED." });
  return { db, project };
}

describe("cover art is generated by the interior's own pipeline", () => {
  it("keeps cover surfaces out of the interior entirely", () => {
    const { db, project } = fixture();
    ensureCoverArtPage(db, owner.id, project.id, "front_cover", "A kitten on a rainy path.");
    ensureCoverArtPage(db, owner.id, project.id, "back_cover", "A quiet garden at dusk.");

    // Every existing reader of page_plans means "the interior", so the covers
    // must not change page counts, the interior PDF, the preview or preflight.
    const interior = listPagePlans(db, owner.id, project.id);
    expect(interior).toHaveLength(1);
    expect(interior[0].pageNumber).toBe(1);
    expect(interior[0].pageRole).toBe("interior");

    expect(listPagePlans(db, owner.id, project.id, "front_cover")).toHaveLength(1);
    expect(listPagePlans(db, owner.id, project.id, "back_cover")).toHaveLength(1);
  });

  it("re-describing a surface updates its one row rather than adding another", () => {
    const { db, project } = fixture();
    const first = ensureCoverArtPage(db, owner.id, project.id, "front_cover", "A kitten on a rainy path.");
    const second = ensureCoverArtPage(db, owner.id, project.id, "front_cover", "A kitten under a red umbrella.");
    expect(second.id).toBe(first.id);
    expect(second.sceneDirection).toBe("A kitten under a red umbrella.");
    expect(listPagePlans(db, owner.id, project.id, "front_cover")).toHaveLength(1);
  });

  it("composes a cover prompt that inherits the story bible and forbids lettering", () => {
    const { db, project } = fixture();
    const page = ensureCoverArtPage(db, owner.id, project.id, "front_cover", "Milo under a red umbrella, looking up.");
    const composed = composePromptFromSavedProject(db, owner.id, {
      projectId: project.id, pagePlanId: page.id,
      generationModel: "Reviewed model", generationEndpoint: "reviewed/model",
      aspectRatio: "1:1", referenceAssetIds: [],
    });
    expect(composed.prompt).toContain("COVER ARTWORK");
    expect(composed.prompt).toContain("FRONT COVER");
    expect(composed.prompt).toContain("Milo under a red umbrella");
    // Continuity with the interior comes from the same brief.
    expect(composed.prompt).toContain("Milo is a small orange kitten with a blue collar.");
    expect(composed.prompt).toContain("Warm watercolor.");
    // The title is typeset at export, so it must never be drawn.
    expect(composed.prompt).toContain(NO_TEXT_RULE_MARKER);
    expect(composed.prompt).not.toContain("SPECIFIC PAGE SCENE");
  });

  it("frames the back cover as a companion image with room for the blurb", () => {
    const { db, project } = fixture();
    const page = ensureCoverArtPage(db, owner.id, project.id, "back_cover", "A quiet garden at dusk.");
    const composed = composePromptFromSavedProject(db, owner.id, {
      projectId: project.id, pagePlanId: page.id,
      generationModel: "Reviewed model", generationEndpoint: "reviewed/model",
      aspectRatio: "1:1", referenceAssetIds: [],
    });
    expect(composed.prompt).toContain("BACK COVER");
    expect(composed.prompt).toMatch(/barcode/i);
  });

  it("keeps a coloring book's cover in full colour while its interior stays line art", () => {
    const { db, project } = fixture("coloring_line_art");
    const cover = ensureCoverArtPage(db, owner.id, project.id, "front_cover", "Milo under a red umbrella.");
    const coverPrompt = composePromptFromSavedProject(db, owner.id, {
      projectId: project.id, pagePlanId: cover.id,
      generationModel: "Reviewed model", generationEndpoint: "reviewed/model", aspectRatio: "1:1", referenceAssetIds: [],
    }).prompt;
    const interiorPrompt = composePromptFromSavedProject(db, owner.id, {
      projectId: project.id, pagePlanId: "cover-art-page-1",
      generationModel: "Reviewed model", generationEndpoint: "reviewed/model", aspectRatio: "1:1", referenceAssetIds: [],
    }).prompt;

    // A cover printed as blank line art would be unsellable.
    expect(coverPrompt).not.toContain("COLORING PAGE LINE ART");
    expect(coverPrompt).toContain("full colour illustration");
    expect(interiorPrompt).toContain("COLORING PAGE LINE ART");
  });

  it("reads a prompt frozen before covers existed as an interior page, not a cover", () => {
    const { db, project } = fixture();
    const composed = composePromptFromSavedProject(db, owner.id, {
      projectId: project.id, pagePlanId: "cover-art-page-1",
      generationModel: "Reviewed model", generationEndpoint: "reviewed/model", aspectRatio: "1:1", referenceAssetIds: [],
    });
    // The snapshot of an older version carries no role at all; treating a
    // missing role as "not interior" would have turned every old page into a
    // cover on its next recompose.
    const legacy = { ...composed.sourceFieldSnapshot, pagePlan: { ...composed.sourceFieldSnapshot.pagePlan, pageRole: undefined } };
    expect(legacy.pagePlan?.pageRole).toBeUndefined();
    expect(composed.prompt).toContain("SPECIFIC PAGE SCENE");
    expect(composed.prompt).not.toContain("COVER ARTWORK");
  });
});

describe("the cover step can generate and then place its art", () => {
  // prepareForGeneration composes against whichever model the deployment has
  // activated, so one has to be active for the pipeline to run at all.
  const previousActive = process.env.FAL_ACTIVE_ENDPOINTS;
  beforeEach(() => { process.env.FAL_ACTIVE_ENDPOINTS = falModelRegistry[0].endpointId; });
  afterEach(() => { if (previousActive === undefined) delete process.env.FAL_ACTIVE_ENDPOINTS; else process.env.FAL_ACTIVE_ENDPOINTS = previousActive; });

  it("takes a description all the way to a displayable image", async () => {
    const { db, project } = fixture();
    const storage = makeStorage();
    const adapter = makeAdapter();
    const service = createFalGenerationService({ adapter, storage, modelApproval: () => true, maxActivePerUser: 50, maxActivePerProject: 50 });
    const router = createAppRouter(db, { storage, generationService: service });
    const caller = router.createCaller({ db, user: owner });

    const saved = await caller.studio.cover.saveArtDirection({ projectId: project.id, pageRole: "front_cover", sceneDirection: "Milo under a red umbrella." });
    const prepared = await caller.studio.prompts.prepareForGeneration({ projectId: project.id, pagePlanIds: [saved.pagePlanId], reuseFrozen: false });
    expect(prepared.prepared).toHaveLength(1);

    const queued = await caller.studio.generationJobs.enqueue({ projectId: project.id, items: prepared.prepared.map((entry) => ({ pagePlanId: entry.pagePlanId, promptVersionId: entry.promptVersionId })) });
    expect(queued.queued).toBe(1);
    await drainQueueOnce(db, service, 2);
    // syncActive leaves a job alone for its first 15 seconds so a just-sent
    // request is not polled immediately; reconcile with no grace period here.
    await service.reconcileActiveJobs(db, owner.id, project.id, 0);

    const coverBoard = await caller.studio.pages.board({ projectId: project.id, pageRole: "front_cover" });
    expect(coverBoard).toHaveLength(1);
    expect(coverBoard[0].latestAsset?.accessUrl).toBeTruthy();

    // The interior board is untouched by any of it.
    const interiorBoard = await caller.studio.pages.board({ projectId: project.id });
    expect(interiorBoard.map((row) => row.pageNumber)).toEqual([1]);

    // And the generated art is now selectable on the cover plan.
    const choices = await caller.studio.cover.artChoices({ projectId: project.id });
    expect(choices.some((choice) => choice.kind === "generated" && choice.id === coverBoard[0].latestAsset?.id)).toBe(true);
  });

  it("suggests a starting description from the story without calling a model", async () => {
    const { db, project } = fixture();
    const router = createAppRouter(db);
    const caller = router.createCaller({ db, user: owner });
    const front = await caller.studio.cover.suggestArtDirection({ projectId: project.id, pageRole: "front_cover" });
    expect(front.sceneDirection).toContain("Milo");
    expect(front.sceneDirection).toMatch(/front-cover/i);
    const back = await caller.studio.cover.suggestArtDirection({ projectId: project.id, pageRole: "back_cover" });
    expect(back.sceneDirection).toMatch(/back-cover|barcode/i);
  });

  it("lets only the owner describe or read a project's cover art", async () => {
    const { db, project } = fixture();
    const router = createAppRouter(db);
    const intruder = router.createCaller({ db, user: stranger });
    await expect(intruder.studio.cover.saveArtDirection({ projectId: project.id, pageRole: "front_cover", sceneDirection: "Hijacked." })).rejects.toMatchObject({ code: "NOT_FOUND" });
    await expect(intruder.studio.cover.artChoices({ projectId: project.id })).rejects.toMatchObject({ code: "NOT_FOUND" });
    await expect(intruder.studio.pages.board({ projectId: project.id, pageRole: "front_cover" })).rejects.toMatchObject({ code: "NOT_FOUND" });
  });
});
