import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import { PDFDocument } from "pdf-lib";
import sharp from "sharp";
import { composeFullWrapCover, validateCoverComposition, type CoverCompositionInput, type CoverTemplateGeometry } from "../server/cover-composer";

const fontBytesPromise = readFile(new URL("../node_modules/@fontsource/noto-sans/files/noto-sans-latin-400-normal.woff", import.meta.url));
const template = (): CoverTemplateGeometry => ({ id: "kdp-template-1", version: "2026-01", fullCoverWidthInches: 17.5, fullCoverHeightInches: 8.75, readingDirection: "ltr", bounds: { back: { x: 0, y: 0, width: 8.5, height: 8.5 }, spine: { x: 8.5, y: 0, width: 0.5, height: 8.5 }, front: { x: 9, y: 0, width: 8.5, height: 8.5 } }, safeZones: { back: { x: 0.25, y: 0.25, width: 8, height: 8 }, spine: { x: 8.56, y: 0.25, width: 0.38, height: 8 }, front: { x: 9.25, y: 0.25, width: 8, height: 8 } }, bleedZones: { back: { x: 0, y: 0, width: 8.5, height: 8.5 }, spine: { x: 8.5, y: 0, width: 0.5, height: 8.5 }, front: { x: 9, y: 0, width: 8.5, height: 8.5 } }, barcodeZone: { x: 6.2, y: 0.5, width: 2, height: 1.2 }, spineSafeZone: { x: 8.56, y: 0.25, width: 0.38, height: 8 } });
async function artBytes() { return sharp({ create: { width: 2550, height: 2550, channels: 3, background: { r: 220, g: 205, b: 190 } } }).png().toBuffer(); }
async function validInput(overrides: Partial<CoverCompositionInput> = {}): Promise<CoverCompositionInput> { const bytes = await artBytes(); const fontBytes = await fontBytesPromise; return { projectId: "book", planVersionId: "plan-1", template: template(), title: "A Quiet Garden", subtitle: "", author: "A. Author", imprint: "", backCoverCopy: "A gentle story.", barcodeDecision: "amazon_placed", spineTextPermitted: false, finalInteriorPageCount: 32, readingDirection: "ltr", art: [{ assetId: "front-art", assetVersion: "v1", checksumSha256: "a".repeat(64), surface: "front", bytes, mimeType: "image/png", placement: template().bounds.front, fullBleed: true, approved: true }, { assetId: "back-art", assetVersion: "v1", checksumSha256: "b".repeat(64), surface: "back", bytes, mimeType: "image/png", placement: template().bounds.back, fullBleed: true, approved: true }], text: [{ id: "title", text: "A Quiet Garden", surface: "front", placement: { x: 9.5, y: 7.2, width: 7.5, height: 0.6 }, fontId: "noto", fontSize: 24, align: "center" }, { id: "back", text: "A gentle story.", surface: "back", placement: { x: 0.5, y: 2, width: 5, height: 2 }, fontId: "noto", fontSize: 12 }], fonts: [{ id: "noto", family: "Noto Sans", bytes: fontBytes, permitted: true }], ...overrides }; }

describe("full-wrap cover composer", () => {
  it("composes a one-page cover and a labeled guide preview", async () => { const input = await validInput(); const final = await composeFullWrapCover(input); const preview = await composeFullWrapCover(input, true); expect((await PDFDocument.load(final.pdfBytes)).getPageCount()).toBe(1); expect((await PDFDocument.load(preview.pdfBytes)).getPageCount()).toBe(1); expect((await PDFDocument.load(preview.pdfBytes)).getSubject()).toMatch(/PREVIEW/); expect((await PDFDocument.load(final.pdfBytes)).getSubject()).toMatch(/Final uploadable/); expect(final.manifest.guideLayersIncluded).toBe(false); expect(preview.manifest.guideLayersIncluded).toBe(true); });
  it("uses imported geometry for page dimensions when the template changes", async () => { const input = await validInput(); const changed = { ...input, template: { ...input.template, id: "kdp-template-2", fullCoverWidthInches: 18.25, fullCoverHeightInches: 9.1 } }; const result = await composeFullWrapCover(changed); const page = (await PDFDocument.load(result.pdfBytes)).getPage(0); expect(page.getWidth()).toBeCloseTo(18.25 * 72); expect(page.getHeight()).toBeCloseTo(9.1 * 72); expect(result.manifest.templateId).toBe("kdp-template-2"); });
  it("blocks barcode-margin violations and ineligible spine text", async () => { const input = await validInput({ barcodeDecision: "creator_supplied", barcodePlacement: { x: 6.1, y: 0.5, width: 2.2, height: 1.2 }, spineTextPermitted: true, finalInteriorPageCount: 78, text: [] }); const report = validateCoverComposition(input); expect(report.issues.map((issue) => issue.code)).toEqual(expect.arrayContaining(["barcode_margin", "spine_text_not_eligible"])); });
  it("blocks missing art and missing fonts", async () => { const input = await validInput({ art: [{ assetId: "missing", assetVersion: "v1", checksumSha256: "c".repeat(64), surface: "front", bytes: new Uint8Array(), mimeType: "image/png", placement: template().bounds.front, fullBleed: true, approved: true }], text: [{ id: "title", text: "Title", surface: "front", placement: template().safeZones.front!, fontId: "missing-font", fontSize: 20 }], fonts: [] }); const report = validateCoverComposition(input); expect(report.issues.map((issue) => issue.code)).toEqual(expect.arrayContaining(["missing_font", "missing_art"])); expect(report.passed).toBe(false); });
  it("warns explicitly that CMYK compliance is unsupported", async () => { const result = await composeFullWrapCover(await validInput()); expect(result.preflight.issues.some((issue) => issue.code === "cmyk_conversion_unsupported" && issue.severity === "warning")).toBe(true); expect(result.manifest.cmyk).toBe("not_converted"); });
});
