import { describe, expect, it } from "vitest";
import { PDFDocument } from "pdf-lib";
import { DEFAULT_KDP_RULESET, DEFAULT_KDP_SOURCE_URLS, evaluatePaperbackPackage, reportHtml, reportJsonBytes, reportPdfBytes, type KdpRuleset, type PaperbackPreflightInput } from "../server/kdp-preflight";

const ruleset: KdpRuleset = { id: "rules-1", version: "2026.08", effectiveDate: "2026-08-01", status: "active", config: DEFAULT_KDP_RULESET, sourceUrls: DEFAULT_KDP_SOURCE_URLS, reviewedByUserId: "admin", reviewedAt: "2026-08-01T00:00:00.000Z", reviewNotes: "Reviewed against official KDP help pages.", createdAt: "2026-08-01T00:00:00.000Z", updatedAt: "2026-08-01T00:00:00.000Z" };
const basePages = Array.from({ length: 24 }, (_, index) => ({ pageNumber: index + 1, blank: false, assetId: `asset-${index + 1}`, effectiveDpi: 300 }));
const baseInput = (): PaperbackPreflightInput => ({ projectId: "book-1", trimWidthInches: 6, trimHeightInches: 9, bleed: false, interiorPageCount: 24, readingDirection: "ltr", interior: { pdfBytes: Buffer.from("interior"), widthInches: 6, heightInches: 9, pageCount: 24, pages: basePages, fontsEmbedded: [], manifestReadingDirection: "ltr", measuredOutsideMarginInches: 0.25, measuredGutterMarginInches: 0.375 }, cover: { pdfBytes: Buffer.from("cover"), pageCount: 1, widthInches: 17.5, heightInches: 9.25, expectedWidthInches: 17.5, expectedHeightInches: 9.25, templateCurrent: true, templateSourceUrl: DEFAULT_KDP_SOURCE_URLS[2], templateFingerprintMatches: true, safeZoneWarnings: [], bleedCovered: true, barcodeClear: true, spineEligible: true, spineTextInsideSafeZone: true, flattened: true, hasGuideContent: false, sourceAssetIds: ["cover-front-v1"] }, expectedInteriorWidthInches: 6, expectedInteriorHeightInches: 9, permittedFontIds: [] });
function codes(input: PaperbackPreflightInput) { return evaluatePaperbackPackage(input, ruleset).results.map((result) => result.ruleId); }

describe("versioned KDP preflight", () => {
  it("passes a complete package for manual review and always records final-authority information", () => { const report = evaluatePaperbackPackage(baseInput(), ruleset); expect(report.readyForManualKdpUploadReview).toBe(true); expect(report.blockingIssueCount).toBe(0); expect(report.ruleset.version).toBe("2026.08"); expect(report.results.some((result) => result.severity === "informational")).toBe(true); });
  it("covers trim, bleed mode, dimensions, page range, margins, DPI, pagination, direction, blanks, and fonts", () => { const input = baseInput(); expect(codes({ ...input, trimWidthInches: 3 })).toContain("paperback.trim_dimensions"); expect(codes({ ...input, bleed: true })).toContain("paperback.interior_pdf_dimensions"); expect(codes({ ...input, interior: { ...input.interior, widthInches: 5 } })).toContain("paperback.interior_pdf_dimensions"); expect(codes({ ...input, interiorPageCount: 10 })).toContain("paperback.page_count_range"); expect(codes({ ...input, interior: { ...input.interior, measuredOutsideMarginInches: 0.1, measuredGutterMarginInches: 0.1 } })).toContain("paperback.margins"); expect(codes({ ...input, interior: { ...input.interior, pages: [{ ...input.interior.pages[0], effectiveDpi: 299 }, ...input.interior.pages.slice(1)] } })).toContain("paperback.image_effective_dpi"); expect(codes({ ...input, interior: { ...input.interior, pages: [{ ...input.interior.pages[0], pageNumber: 2 }, ...input.interior.pages.slice(1)] } })).toContain("paperback.sequential_pagination"); expect(codes({ ...input, interior: { ...input.interior, manifestReadingDirection: "rtl" } })).toContain("paperback.reading_direction"); expect(codes({ ...input, interior: { ...input.interior, pages: input.interior.pages.map((page, index) => ({ ...page, blank: index < 3 })) } })).toContain("paperback.blank_pages"); expect(codes({ ...input, interior: { ...input.interior, pages: [{ ...input.interior.pages[0], textFontIds: ["font-x"] }] } })).toContain("paperback.font_embedding"); });
  it("covers cover count, geometry, provenance, safe zones, bleed, barcode, spine, transparency, guides, and size", () => { const input = baseInput(); expect(codes({ ...input, cover: { ...input.cover, pageCount: 2 } })).toContain("paperback.cover_page_count"); expect(codes({ ...input, cover: { ...input.cover, widthInches: 1 } })).toContain("paperback.cover_page_count"); expect(codes({ ...input, cover: { ...input.cover, templateCurrent: false } })).toContain("paperback.template_provenance"); expect(codes({ ...input, cover: { ...input.cover, safeZoneWarnings: ["title crosses front safe zone"] } })).toContain("paperback.cover_manual_review"); expect(codes({ ...input, cover: { ...input.cover, bleedCovered: false } })).toContain("paperback.cover_bleed"); expect(codes({ ...input, cover: { ...input.cover, barcodeClear: false } })).toContain("paperback.barcode_clearance"); expect(codes({ ...input, cover: { ...input.cover, spineEligible: false } })).toContain("paperback.spine_eligibility"); expect(codes({ ...input, cover: { ...input.cover, flattened: false } })).toContain("paperback.flattened_cover"); expect(codes({ ...input, cover: { ...input.cover, hasGuideContent: true } })).toContain("paperback.cover_guides_removed"); const smallRuleset = { ...ruleset, config: { paperback: { ...DEFAULT_KDP_RULESET.paperback, coverMaxBytes: 1, recommendedCoverBytes: 1 } } }; expect(evaluatePaperbackPackage(input, smallRuleset).results.map((result) => result.ruleId)).toContain("paperback.cover_file_size"); });
  it("identifies exact region, measured value, source asset, remedy, and source URL for each finding", () => { const input = baseInput(); input.interior.pages[0].effectiveDpi = 240; const result = evaluatePaperbackPackage(input, ruleset).results.find((item) => item.ruleId === "paperback.image_effective_dpi")!; expect(result.region).toBe("interior page 1"); expect(result.measured).toContain("240"); expect(result.sourceAsset).toBe("asset-1"); expect(result.remedy.length).toBeGreaterThan(10); expect(result.sourceUrl).toMatch(/^https:\/\//); });
  it("exports stable JSON and readable HTML/PDF reports", async () => { const report = evaluatePaperbackPackage(baseInput(), ruleset); const json = reportJsonBytes(report); const html = reportHtml(report); const pdf = await reportPdfBytes(report); expect(Buffer.from(json).toString()).toContain("kdp-preflight-report-v1"); expect(html).toContain("KDP Paperback Preflight"); expect((await PDFDocument.load(pdf)).getPageCount()).toBeGreaterThan(0); });
});
