import { describe, expect, it } from "vitest";
import { createDatabase, createProject, upsertUser } from "../server/db";
import { addProvenanceEntry, assertPublishingReadyForExport, classifyContentPolicy, createPublishingMetadataVersion, finalizePublishingMetadataVersion } from "../server/publishing";

const owner = { id: "publishing-owner", name: "Publishing Owner", email: "publishing@example.com" };
function setup() { const db = createDatabase(":memory:"); upsertUser(db, owner); const project = createProject(db, owner.id, { id: "publishing-project", name: "Metadata Book", brief: "A book." }); return { db, project }; }
const metadata = { title: "The Garden", subtitle: "A small story", language: "en-US", keywordPhrases: ["garden story", "picture book", "nature kids", "gentle bedtime", "friendship tale", "read aloud", "spring adventure"], readingDirection: "ltr" as const, printSettings: { trim: "8x10", paper: "white" }, rightsOwner: "The Creator", aiDisclosureConfirmed: true, rightsAttestationConfirmed: true as const };

describe("publishing metadata and provenance", () => {
  it("classifies prohibited, ambiguous, and ordinary requests", () => { expect(classifyContentPolicy("Draw Mickey Mouse in a new adventure").status).toBe("blocked"); expect(classifyContentPolicy("similar to a familiar storybook mood").status).toBe("needs_human_review"); expect(classifyContentPolicy("original watercolor garden with soft shapes").status).toBe("cleared"); });
  it("requires exactly seven keywords and rights attestation", () => { const { db, project } = setup(); expect(createPublishingMetadataVersion(db, owner.id, project.id, { ...metadata, keywordPhrases: ["one"] }).errors).toContain("exactly seven keyword phrases are required"); expect(createPublishingMetadataVersion(db, owner.id, project.id, { ...metadata, rightsAttestationConfirmed: false as never }).errors).toContain("rights attestation is required before export"); });
  it("requires complete AI-generated provenance fields and owner approval", () => { const { db, project } = setup(); expect(() => addProvenanceEntry(db, owner.id, project.id, undefined, { elementType: "image", elementKey: "cover-front", classification: "ai_generated", ownerApproval: false, rightsAttestation: false })).toThrow("AI-generated provenance requires"); const id = addProvenanceEntry(db, owner.id, project.id, undefined, { elementType: "image", elementKey: "cover-front", classification: "ai_generated", modelEndpoint: "reviewed/endpoint", promptVersionId: "prompt-1", outputTimestamp: new Date().toISOString(), ownerApproval: true, rightsAttestation: true }); expect(id).toBeTruthy(); });
  it("finalizes a metadata version and blocks export until it is final", () => { const { db, project } = setup(); const created = createPublishingMetadataVersion(db, owner.id, project.id, metadata); expect(created.errors).toEqual([]); expect(() => assertPublishingReadyForExport(db, owner.id, project.id)).toThrow("final publishing metadata"); finalizePublishingMetadataVersion(db, owner.id, project.id, created.id); expect(assertPublishingReadyForExport(db, owner.id, project.id).metadataVersionId).toBe(created.id); });
  it("blocks final export when a policy review is blocked", () => { const { db, project } = setup(); const created = createPublishingMetadataVersion(db, owner.id, project.id, metadata); finalizePublishingMetadataVersion(db, owner.id, project.id, created.id); db.prepare(`INSERT INTO content_policy_reviews (id, user_id, project_id, subject_type, subject_id, content_hash, status, created_at, updated_at) VALUES ('review-blocked', ?, ?, 'prompt', 'prompt-1', 'hash', 'blocked', ?, ?)`).run(owner.id, project.id, new Date().toISOString(), new Date().toISOString()); expect(() => assertPublishingReadyForExport(db, owner.id, project.id)).toThrow("blocked content-policy"); });
});
