import crypto from "node:crypto";
import { PDFDocument, rgb, type PDFFont, type PDFImage, type PDFPage } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import sharp, { type Metadata } from "sharp";
import type { PrivateStorage } from "./storage";
import { readPrivateStorageBytes } from "./storage";
import type { AppDatabase } from "./db";
import { getProjectForUser } from "./db";
import { getCoverPlanVersion } from "./cover-desk";

export const KDP_COVER_MAX_BYTES = 650 * 1024 * 1024;
export const KDP_COVER_RECOMMENDED_MAX_BYTES = 40 * 1024 * 1024;
const PT = 72;
export type CoverRect = { x: number; y: number; width: number; height: number };
export type CoverSurface = "back" | "spine" | "front";
export type CoverTemplateGeometry = { id: string; version?: string; fullCoverWidthInches: number; fullCoverHeightInches: number; bounds: Record<CoverSurface, CoverRect>; safeZones: Partial<Record<CoverSurface, CoverRect>>; bleedZones: Partial<Record<CoverSurface, CoverRect>>; barcodeZone?: CoverRect; spineSafeZone?: CoverRect; readingDirection: "ltr" | "rtl" };
export type CoverArtPlacement = { assetId: string; assetVersion: string; checksumSha256: string; surface: CoverSurface; bytes: Uint8Array; mimeType: "image/png" | "image/jpeg" | "image/webp"; placement: CoverRect; fullBleed?: boolean; approved: boolean };
export type CoverTextPlacement = { id: string; text: string; surface: CoverSurface; placement: CoverRect; fontId: string; fontSize: number; align?: "left" | "center" | "right" };
export type CoverFont = { id: string; family: string; bytes: Uint8Array; permitted: boolean };
export type CoverCompositionInput = { projectId: string; planVersionId: string; template: CoverTemplateGeometry; title: string; subtitle: string; author: string; imprint: string; backCoverCopy: string; barcodeDecision: "amazon_placed" | "creator_supplied"; spineTextPermitted: boolean; finalInteriorPageCount: number; readingDirection: "ltr" | "rtl"; art: CoverArtPlacement[]; text: CoverTextPlacement[]; fonts: CoverFont[]; barcodePlacement?: CoverRect };
export type CoverIssue = { code: string; severity: "blocking" | "warning"; surface?: CoverSurface; message: string; details?: Record<string, unknown> };
export type CoverPreflight = { issues: CoverIssue[]; blockingIssueCount: number; warningCount: number; passed: boolean; cmYKStatus: "warning_unsupported"; outputBytes?: number };
export type CoverCompositionManifest = { manifestVersion: "full-wrap-cover-v1"; projectId: string; planVersionId: string; templateId: string; templateVersion: string | null; readingDirection: "ltr" | "rtl"; physicalPageSizeInches: { width: number; height: number }; surfaces: Record<CoverSurface, CoverRect>; safeZones: Partial<Record<CoverSurface, CoverRect>>; bleedZones: Partial<Record<CoverSurface, CoverRect>>; barcodeZone: CoverRect | null; spineSafeZone: CoverRect | null; art: Array<{ assetId: string; assetVersion: string; checksumSha256: string; surface: CoverSurface; placement: CoverRect; fullBleed: boolean }>; text: Array<{ id: string; surface: CoverSurface; placement: CoverRect; fontId: string; fontSize: number }>; guideLayersIncluded: boolean; cmyk: "not_converted"; preflight: { blockingIssueCount: number; warningCount: number } };

function contains(outer: CoverRect, inner: CoverRect): boolean { return inner.x >= outer.x && inner.y >= outer.y && inner.x + inner.width <= outer.x + outer.width && inner.y + inner.height <= outer.y + outer.height; }
function intersects(first: CoverRect, second: CoverRect): boolean { return first.x < second.x + second.width && first.x + first.width > second.x && first.y < second.y + second.height && first.y + first.height > second.y; }
function ptRect(rect: CoverRect): [number, number, number, number] { return [rect.x * PT, rect.y * PT, rect.width * PT, rect.height * PT]; }
function rectOptions(rect: CoverRect): { x: number; y: number; width: number; height: number } { const [x, y, width, height] = ptRect(rect); return { x, y, width, height }; }
function nearWhite(value: number): boolean { return value > 247; }
function parseRect(value: unknown): CoverRect | undefined { if (!value || typeof value !== "object") return undefined; const item = value as Record<string, unknown>; const values = [item.x, item.y, item.width, item.height].map(Number); return values.every(Number.isFinite) && values.every((number) => number >= 0) ? { x: values[0], y: values[1], width: values[2], height: values[3] } : undefined; }
function fontFor(fonts: Map<string, PDFFont>, id: string): PDFFont | undefined { return fonts.get(id) ?? fonts.get("default"); }
function drawText(page: PDFPage, font: PDFFont, block: CoverTextPlacement): void { const [x, y, width, height] = ptRect(block.placement); const size = block.fontSize; const textWidth = font.widthOfTextAtSize(block.text, size); const textX = block.align === "center" ? x + (width - textWidth) / 2 : block.align === "right" ? x + width - textWidth : x; page.drawText(block.text, { x: textX, y: y + height - size, size, font, color: rgb(0.05, 0.06, 0.08), maxWidth: width }); }
function drawCoverImage(page: PDFPage, image: PDFImage, placement: CoverRect): void { const [x, y, width, height] = ptRect(placement); page.drawImage(image, { x, y, width, height }); }

export function validateCoverComposition(input: CoverCompositionInput): CoverPreflight {
  const issues: CoverIssue[] = [];
  const template = input.template;
  if (!template.id || template.fullCoverWidthInches <= 0 || template.fullCoverHeightInches <= 0) issues.push({ code: "missing_template_geometry", severity: "blocking", message: "A current imported KDP template with full-cover dimensions is required; cover measurements are never reconstructed from a formula." });
  for (const surface of ["back", "spine", "front"] as CoverSurface[]) { if (!template.bounds[surface]) issues.push({ code: "missing_surface_bounds", severity: "blocking", surface, message: `The imported template has no ${surface} bounds.` }); }
  if (input.spineTextPermitted && input.finalInteriorPageCount < 79) issues.push({ code: "spine_text_not_eligible", severity: "blocking", surface: "spine", message: "Spine text is not permitted below 79 paperback pages." });
  const permittedFontIds = new Set(input.fonts.filter((font) => font.permitted).map((font) => font.id));
  for (const block of input.text) if (!permittedFontIds.has(block.fontId)) issues.push({ code: "missing_font", severity: "blocking", surface: block.surface, message: `Font ${block.fontId} is missing or not permitted for deterministic cover typography.` });
  if (input.barcodeDecision === "creator_supplied" && !input.barcodePlacement) issues.push({ code: "missing_barcode_placement", severity: "blocking", surface: "back", message: "A creator-supplied barcode requires a placement inside the imported barcode exclusion geometry." });
  if (input.barcodePlacement && template.barcodeZone && !contains(template.barcodeZone, input.barcodePlacement)) issues.push({ code: "barcode_margin", severity: "blocking", surface: "back", message: "The supplied barcode is outside the imported barcode-safe placement zone.", details: { barcodeZone: template.barcodeZone } });
  if (input.barcodePlacement && !template.barcodeZone) issues.push({ code: "missing_barcode_geometry", severity: "blocking", surface: "back", message: "The imported template does not provide barcode exclusion geometry." });
  const allText = input.text;
  for (const block of allText) {
    const safe = block.surface === "spine" ? template.spineSafeZone ?? template.safeZones.spine : template.safeZones[block.surface];
    if (!safe || !contains(safe, block.placement)) issues.push({ code: block.surface === "spine" ? "spine_safe_zone" : "text_safe_zone", severity: "blocking", surface: block.surface, message: `Text block ${block.id} is outside the imported ${block.surface} safe zone.` });
    if (block.surface === "spine" && !input.spineTextPermitted) issues.push({ code: "spine_text_disabled", severity: "blocking", surface: "spine", message: "This cover plan does not permit spine text." });
  }
  for (const art of input.art) {
    if (!art.approved) issues.push({ code: "unapproved_art", severity: "blocking", surface: art.surface, message: `Cover artwork ${art.assetId} is not approved.` });
    if (!art.bytes.byteLength) issues.push({ code: "missing_art", severity: "blocking", surface: art.surface, message: `Approved cover artwork ${art.assetId} could not be resolved.` });
    const surfaceBounds = template.bounds[art.surface]; const bleed = template.bleedZones[art.surface] ?? surfaceBounds;
    if (art.fullBleed && (!bleed || !contains(bleed, art.placement))) issues.push({ code: "bleed_not_covered", severity: "blocking", surface: art.surface, message: `Full-bleed artwork ${art.assetId} does not cover the imported ${art.surface} bleed region.` });
    const safe = template.safeZones[art.surface];
    if (!art.fullBleed && safe && !contains(safe, art.placement)) issues.push({ code: "art_safe_zone", severity: "warning", surface: art.surface, message: `Artwork ${art.assetId} crosses the imported ${art.surface} safe zone.` });
    if (art.surface === "back" && !art.fullBleed && template.barcodeZone && intersects(art.placement, template.barcodeZone)) issues.push({ code: "barcode_exclusion", severity: "blocking", surface: "back", message: `Artwork ${art.assetId} overlaps the imported barcode exclusion zone.` });
  }
  for (const block of input.text) if (block.surface === "back" && template.barcodeZone && intersects(block.placement, template.barcodeZone)) issues.push({ code: "barcode_exclusion", severity: "blocking", surface: "back", message: `Text block ${block.id} overlaps the imported barcode exclusion zone.` });
  if (input.readingDirection !== template.readingDirection) issues.push({ code: "reading_direction_mismatch", severity: "blocking", message: "The cover plan reading direction does not match the imported template direction." });
  issues.push({ code: "cmyk_conversion_unsupported", severity: "warning", message: "This runtime/library chain does not provide reliable CMYK conversion; the output is not claimed to be CMYK-compliant." });
  const blockingIssueCount = issues.filter((issue) => issue.severity === "blocking").length;
  return { issues, blockingIssueCount, warningCount: issues.length - blockingIssueCount, passed: blockingIssueCount === 0, cmYKStatus: "warning_unsupported" };
}

async function flattenIfNeeded(art: CoverArtPlacement): Promise<{ bytes: Buffer; mimeType: "image/png" | "image/jpeg"; metadata: Metadata; possibleWhiteEdge: boolean }> {
  const source = sharp(art.bytes); const metadata = await source.metadata();
  const stats = await source.stats();
  const edge = await source.clone().ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const channels = edge.info.channels; const edgePixels: number[] = [];
  for (let y = 0; y < edge.info.height; y += Math.max(1, Math.floor(edge.info.height / 24))) for (let x = 0; x < edge.info.width; x += Math.max(1, Math.floor(edge.info.width / 24))) { if (x < 2 || y < 2 || x >= edge.info.width - 2 || y >= edge.info.height - 2) { const offset = (y * edge.info.width + x) * channels; edgePixels.push((edge.data[offset] + edge.data[offset + 1] + edge.data[offset + 2]) / 3); } }
  const possibleWhiteEdge = edgePixels.length > 0 && edgePixels.filter(nearWhite).length / edgePixels.length > 0.75 && Number(stats.channels?.[0]?.mean ?? 0) < 245;
  if (metadata.hasAlpha || art.mimeType === "image/webp") return { bytes: await source.flatten({ background: "#ffffff" }).jpeg({ quality: 100 }).toBuffer(), mimeType: "image/jpeg", metadata, possibleWhiteEdge };
  return { bytes: Buffer.from(art.bytes), mimeType: art.mimeType, metadata, possibleWhiteEdge };
}

export async function composeFullWrapCover(input: CoverCompositionInput, preview = false): Promise<{ pdfBytes: Uint8Array; manifest: CoverCompositionManifest; preflight: CoverPreflight }> {
  const preflight = validateCoverComposition(input);
  const normalizedArt: Array<CoverArtPlacement & { normalizedBytes?: Buffer; normalizedMimeType?: "image/png" | "image/jpeg" }> = [];
  for (const art of input.art) { try { const normalized = await flattenIfNeeded(art); normalizedArt.push({ ...art, normalizedBytes: normalized.bytes, normalizedMimeType: normalized.mimeType }); if (normalized.possibleWhiteEdge && art.fullBleed) preflight.issues.push({ code: "possible_white_edge", severity: "warning", surface: art.surface, message: `Full-bleed artwork ${art.assetId} has a predominantly white edge; visually inspect the final preview for an unintended white border.` }); const metadata = normalized.metadata; const dpiX = (metadata.width ?? 0) / art.placement.width; const dpiY = (metadata.height ?? 0) / art.placement.height; const dpi = Math.min(dpiX, dpiY); if (dpi < 300) preflight.issues.push({ code: "cover_art_low_dpi", severity: "blocking", surface: art.surface, message: `Cover artwork ${art.assetId} is ${dpi.toFixed(1)} effective DPI; placement requires at least ${Math.ceil(art.placement.width * 300)} × ${Math.ceil(art.placement.height * 300)} pixels.`, details: { widthPixels: metadata.width, heightPixels: metadata.height, effectiveDpi: dpi, requiredWidthPixels: Math.ceil(art.placement.width * 300), requiredHeightPixels: Math.ceil(art.placement.height * 300) } }); } catch { preflight.issues.push({ code: "corrupt_art", severity: "blocking", surface: art.surface, message: `Cover artwork ${art.assetId} could not be decoded.` }); } }
  preflight.blockingIssueCount = preflight.issues.filter((issue) => issue.severity === "blocking").length; preflight.warningCount = preflight.issues.length - preflight.blockingIssueCount; preflight.passed = preflight.blockingIssueCount === 0;
  const manifest: CoverCompositionManifest = { manifestVersion: "full-wrap-cover-v1", projectId: input.projectId, planVersionId: input.planVersionId, templateId: input.template.id, templateVersion: input.template.version ?? null, readingDirection: input.readingDirection, physicalPageSizeInches: { width: input.template.fullCoverWidthInches, height: input.template.fullCoverHeightInches }, surfaces: input.template.bounds, safeZones: input.template.safeZones, bleedZones: input.template.bleedZones, barcodeZone: input.template.barcodeZone ?? null, spineSafeZone: input.template.spineSafeZone ?? null, art: input.art.map((art) => ({ assetId: art.assetId, assetVersion: art.assetVersion, checksumSha256: art.checksumSha256, surface: art.surface, placement: art.placement, fullBleed: Boolean(art.fullBleed) })), text: input.text.map((block) => ({ id: block.id, surface: block.surface, placement: block.placement, fontId: block.fontId, fontSize: block.fontSize })), guideLayersIncluded: preview, cmyk: "not_converted", preflight: { blockingIssueCount: preflight.blockingIssueCount, warningCount: preflight.warningCount } };
  if (!preflight.passed && !preview) return { pdfBytes: new Uint8Array(), manifest, preflight };
  const pdf = await PDFDocument.create(); pdf.registerFontkit(fontkit); pdf.setTitle(preview ? `${input.projectId} full-wrap preview` : `${input.projectId} full-wrap cover`); pdf.setSubject(preview ? "PREVIEW — NOT FOR UPLOAD" : "Final uploadable cover; no guides"); pdf.setAuthor("KDP Kids Book Studio"); pdf.setCreationDate(new Date(0)); pdf.setModificationDate(new Date(0));
  const fontMap = new Map<string, PDFFont>(); for (const font of input.fonts) if (font.permitted) fontMap.set(font.id, await pdf.embedFont(font.bytes, { subset: false }));
  const page = pdf.addPage([input.template.fullCoverWidthInches * PT, input.template.fullCoverHeightInches * PT]);
  for (const art of normalizedArt) if (art.normalizedBytes && art.normalizedMimeType) { const image = art.normalizedMimeType === "image/png" ? await pdf.embedPng(art.normalizedBytes) : await pdf.embedJpg(art.normalizedBytes); drawCoverImage(page, image, art.placement); }
  for (const block of input.text) { const font = fontFor(fontMap, block.fontId); if (font) drawText(page, font, block); }
  if (preview) { for (const surface of ["back", "spine", "front"] as CoverSurface[]) { const bounds = input.template.bounds[surface]; const safe = input.template.safeZones[surface]; const bleed = input.template.bleedZones[surface]; if (bleed) page.drawRectangle({ ...rectOptions(bleed), borderColor: rgb(0.75, 0.2, 0.1), borderWidth: 0.7, opacity: 0.5 }); page.drawRectangle({ ...rectOptions(bounds), borderColor: rgb(0.8, 0.4, 0.1), borderWidth: 0.8, opacity: 0.6 }); if (safe) page.drawRectangle({ ...rectOptions(safe), borderColor: rgb(0.1, 0.5, 0.35), borderWidth: 0.8, opacity: 0.7 }); } if (input.template.barcodeZone) page.drawRectangle({ ...rectOptions(input.template.barcodeZone!), borderColor: rgb(0.75, 0.1, 0.1), borderWidth: 1.2, opacity: 0.7 }); const labelFont = fontMap.get("default"); if (labelFont) page.drawText("PREVIEW — NOT FOR UPLOAD", { x: 8, y: 8, size: 8, font: labelFont, color: rgb(0.75, 0.1, 0.1) }); }
  const pdfBytes = await pdf.save({ useObjectStreams: false, addDefaultPage: false }); preflight.outputBytes = pdfBytes.byteLength; if (pdfBytes.byteLength > KDP_COVER_MAX_BYTES) { preflight.issues.push({ code: "cover_file_too_large", severity: "blocking", message: `The cover PDF is ${pdfBytes.byteLength} bytes, above the current 650 MB KDP conversion limit.` }); preflight.blockingIssueCount += 1; preflight.passed = false; } else if (pdfBytes.byteLength > KDP_COVER_RECOMMENDED_MAX_BYTES) preflight.issues.push({ code: "cover_file_large", severity: "warning", message: "The cover PDF is above KDP’s recommended 40 MB size and may process slowly." }); return { pdfBytes, manifest: { ...manifest, preflight: { blockingIssueCount: preflight.blockingIssueCount, warningCount: preflight.warningCount } }, preflight };
}

function jsonRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
export async function composeCoverExport(db: AppDatabase, storage: PrivateStorage, userId: string, projectId: string, input: { planVersionId: string; templateImportId: string; frontArtPlacement?: CoverRect; backArtPlacement?: CoverRect; spineTextPlacement?: CoverRect; barcodePlacement?: CoverRect; fonts: CoverFont[] }): Promise<{ runId: string; status: "blocked" | "completed"; finalPdfAccessUrl: string | null; previewPdfAccessUrl: string; manifest: CoverCompositionManifest; preflight: CoverPreflight }> {
  const project = getProjectForUser(db, userId, projectId); const plan = getCoverPlanVersion(db, userId, input.planVersionId); if (!project || !plan || plan.projectId !== projectId) throw new Error("Cover plan not found.");
  const template = db.prepare(`SELECT id, full_cover_width_inches AS fullWidth, full_cover_height_inches AS fullHeight, bounds_json AS bounds, safe_zones_json AS safeZones, bleed_zones_json AS bleedZones, barcode_margin_json AS barcodeMargin, spine_safe_zone_json AS spineSafeZone, status FROM cover_template_imports WHERE user_id = ? AND project_id = ? AND id = ?`).get(userId, projectId, input.templateImportId) as Record<string, unknown> | undefined; if (!template || template.status !== "current") throw new Error("A current imported cover template is required.");
  const geometry = { id: String(template.id), fullCoverWidthInches: Number(template.fullWidth), fullCoverHeightInches: Number(template.fullHeight), bounds: jsonRecord(template.bounds) as CoverTemplateGeometry["bounds"], safeZones: jsonRecord(template.safeZones) as CoverTemplateGeometry["safeZones"], bleedZones: jsonRecord(template.bleedZones) as CoverTemplateGeometry["bleedZones"], barcodeZone: parseRect(jsonRecord(template.barcodeMargin).zone), spineSafeZone: parseRect(jsonRecord(template.spineSafeZone).zone), readingDirection: plan.readingDirection };
  const art: CoverArtPlacement[] = []; for (const role of [{ id: plan.frontArtAssetId, surface: "front" as const, placement: input.frontArtPlacement }, { id: plan.backArtAssetId, surface: "back" as const, placement: input.backArtPlacement }]) if (role.id) { const asset = db.prepare(`SELECT id, 'generated' AS assetKind, storage_reference AS storageReference, mime_type AS mimeType, checksum_sha256 AS checksum, updated_at AS updatedAt, status FROM generated_assets WHERE user_id = ? AND project_id = ? AND id = ? UNION ALL SELECT id, 'reference' AS assetKind, storage_key AS storageReference, mime_type AS mimeType, content_hash_sha256 AS checksum, updated_at AS updatedAt, status FROM reference_assets WHERE user_id = ? AND project_id = ? AND id = ? AND status = 'active' LIMIT 1`).get(userId, projectId, role.id, userId, projectId, role.id) as Record<string, unknown> | undefined; if (asset) art.push({ assetId: String(asset.id), assetVersion: String(asset.updatedAt), checksumSha256: String(asset.checksum), surface: role.surface, bytes: await readPrivateStorageBytes(String(asset.storageReference)).catch(() => new Uint8Array()), mimeType: asset.mimeType === "image/png" ? "image/png" : asset.mimeType === "image/jpeg" ? "image/jpeg" : "image/webp", placement: role.placement ?? geometry.bounds[role.surface], fullBleed: true, approved: asset.assetKind === "reference" ? asset.status === "active" : asset.status === "approved" }); }
  const text: CoverTextPlacement[] = [{ id: "title", text: plan.title, surface: "front", placement: { x: geometry.bounds.front.x + 0.5, y: geometry.bounds.front.y + geometry.bounds.front.height - 1.2, width: Math.max(0, geometry.bounds.front.width - 1), height: 0.6 }, fontId: "default", fontSize: 24, align: "center" }, { id: "author", text: plan.author, surface: "front", placement: { x: geometry.bounds.front.x + 0.5, y: geometry.bounds.front.y + 0.35, width: Math.max(0, geometry.bounds.front.width - 1), height: 0.4 }, fontId: "default", fontSize: 14, align: "center" }, { id: "back-copy", text: plan.backCoverCopy, surface: "back", placement: { x: geometry.bounds.back.x + 0.5, y: geometry.bounds.back.y + 1.25, width: Math.max(0, geometry.bounds.back.width - 1), height: Math.max(0.5, geometry.bounds.back.height - 2) }, fontId: "default", fontSize: 12 }]; if (plan.spineTextPermitted) text.push({ id: "spine-title", text: plan.title, surface: "spine", placement: input.spineTextPlacement ?? geometry.spineSafeZone ?? geometry.bounds.spine, fontId: "default", fontSize: 10, align: "center" });
  const fonts = input.fonts.length ? input.fonts : [{ id: "default", family: "Noto Sans", bytes: await readFileFallbackFont(), permitted: true }]; const composition: CoverCompositionInput = { projectId, planVersionId: plan.id, template: geometry, title: plan.title, subtitle: plan.subtitle, author: plan.author, imprint: plan.imprint, backCoverCopy: plan.backCoverCopy, barcodeDecision: plan.barcodeDecision, spineTextPermitted: plan.spineTextPermitted, finalInteriorPageCount: plan.finalInteriorPageCount, readingDirection: plan.readingDirection, art, text, fonts, barcodePlacement: input.barcodePlacement }; const final = await composeFullWrapCover(composition); const preview = await composeFullWrapCover(composition, true); const runId = crypto.randomUUID(); const base = `${userId}/projects/${projectId}/cover-exports/${runId}`; const manifestRef = `${base}/manifest.json`; const preflightRef = `${base}/preflight.json`; const previewRef = `${base}/preview.pdf`; const finalRef = `${base}/cover.pdf`; await storage.put(manifestRef, Buffer.from(JSON.stringify(final.manifest)), "application/json"); await storage.put(preflightRef, Buffer.from(JSON.stringify(final.preflight)), "application/json"); await storage.put(previewRef, preview.pdfBytes, "application/pdf"); if (final.preflight.passed) await storage.put(finalRef, final.pdfBytes, "application/pdf"); const status = final.preflight.passed ? "completed" : "blocked"; const now = new Date().toISOString(); db.prepare(`INSERT INTO cover_export_runs (id, user_id, project_id, cover_plan_version_id, template_import_id, final_pdf_storage_reference, preview_pdf_storage_reference, manifest_storage_reference, preflight_storage_reference, blocking_issue_count, warning_count, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(runId, userId, projectId, plan.id, input.templateImportId, status === "completed" ? finalRef : null, previewRef, manifestRef, preflightRef, final.preflight.blockingIssueCount, final.preflight.warningCount, status, now, now); return { runId, status, finalPdfAccessUrl: status === "completed" ? await storage.createAccessUrl(finalRef, 900) : null, previewPdfAccessUrl: await storage.createAccessUrl(previewRef, 900), manifest: final.manifest, preflight: final.preflight };
}
async function readFileFallbackFont(): Promise<Uint8Array> { const candidates = ["node_modules/@fontsource/noto-sans/files/noto-sans-latin-400-normal.woff", "node_modules/.pnpm/@fontsource+noto-sans@5.3.0/node_modules/@fontsource/noto-sans/files/noto-sans-latin-400-normal.woff"]; for (const candidate of candidates) { try { return await (await import("node:fs/promises")).readFile(candidate); } catch { /* try next packaged path */ } } throw new Error("No permitted packaged font is available for deterministic cover typography."); }
