import crypto from "node:crypto";
import { PassThrough, Readable } from "node:stream";
import * as archiver from "archiver";
import type { AppDatabase } from "./db";
import { getProjectForUser } from "./db";
import type { PrivateStorage } from "./storage";
import { readPrivateStorageBytes } from "./storage";
import { assertPublishingReadyForExport } from "./publishing";

export type ListingMetadata = { title: string; subtitle?: string; author: string; description?: string; keywords?: string; categories?: string; language?: string; }; 
export type FinalExportInput = { projectId: string; validationRunId: string; interiorExportRunId: string; coverExportRunId: string; frozenProjectVersion: string; confirmFinalProjectVersion: boolean; listingMetadata: ListingMetadata; approvedSourceImageIds?: string[]; retentionDays?: number };
export type ExportArtifact = { path: string; storageReference: string | null; sha256: string | null; required: boolean; uploadReady: boolean };
export type FinalExportResult = { exportPackageId: string; frozenProjectVersion: string; status: "completed"; zipAccessUrl: string; artifacts: ExportArtifact[]; expiresAt: string };
export function isExportDownloadable(retentionStatus: string, expiresAt: string | null): boolean { return retentionStatus !== "expired" && (!expiresAt || new Date(expiresAt).getTime() > Date.now()); }

function stableJson(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`; return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stableJson(item)}`).join(",")}}`; }
function hashBytes(bytes: Uint8Array): string { return crypto.createHash("sha256").update(bytes).digest("hex"); }
function csvCell(value: unknown): string { const text = String(value ?? ""); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
function listingCsv(metadata: ListingMetadata): string { return `${Object.keys(metadata).map(csvCell).join(",")}\n${Object.values(metadata).map(csvCell).join(",")}\n`; }
function streamFor(storage: PrivateStorage, key: string): Readable { return (storage.createReadStream ? storage.createReadStream(key) : Readable.from([readPrivateStorageBytes(key)])) as Readable; }
async function streamHash(storage: PrivateStorage, key: string): Promise<{ sha256: string; bytes: number }> { const hash = crypto.createHash("sha256"); let bytes = 0; const stream = streamFor(storage, key) as AsyncIterable<Buffer>; for await (const chunk of stream) { const buffer = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk); hash.update(buffer); bytes += buffer.byteLength; } return { sha256: hash.digest("hex"), bytes }; }
function frozenVersion(projectUpdatedAt: string, input: Pick<FinalExportInput, "validationRunId" | "interiorExportRunId" | "coverExportRunId">): string { return hashBytes(Buffer.from(stableJson({ projectUpdatedAt, validationRunId: input.validationRunId, interiorExportRunId: input.interiorExportRunId, coverExportRunId: input.coverExportRunId }))); }

export async function createFinalExport(db: AppDatabase, storage: PrivateStorage, userId: string, input: FinalExportInput): Promise<FinalExportResult> {
  if (!input.confirmFinalProjectVersion) throw new Error("Explicit confirmation of the finalized project version is required.");
  const project = getProjectForUser(db, userId, input.projectId); if (!project) throw new Error("Project not found.");
  assertPublishingReadyForExport(db, userId, input.projectId);
  const computedVersion = frozenVersion(project.updatedAt, input); if (computedVersion !== input.frozenProjectVersion) throw new Error("The selected project version is stale; refresh validation and export artifacts.");
  const validation = db.prepare(`SELECT id, status, blocking_issue_count AS blockingCount, report_pdf_storage_reference AS reportPdf FROM kdp_preflight_runs WHERE user_id = ? AND project_id = ? AND id = ?`).get(userId, input.projectId, input.validationRunId) as Record<string, unknown> | undefined;
  if (!validation || validation.status !== "ready_for_manual_review" || Number(validation.blockingCount) !== 0) throw new Error("A completed validation run with no blocking failures is required before final export.");
  const interior = db.prepare(`SELECT interior_pdf_storage_reference AS interiorRef, status FROM interior_export_runs WHERE user_id = ? AND project_id = ? AND id = ?`).get(userId, input.projectId, input.interiorExportRunId) as Record<string, unknown> | undefined;
  const cover = db.prepare(`SELECT final_pdf_storage_reference AS coverRef, preview_pdf_storage_reference AS previewRef, status FROM cover_export_runs WHERE user_id = ? AND project_id = ? AND id = ?`).get(userId, input.projectId, input.coverExportRunId) as Record<string, unknown> | undefined;
  if (!interior || interior.status !== "completed" || !interior.interiorRef) throw new Error("A completed final interior PDF is required.");
  if (!cover || cover.status !== "completed" || !cover.coverRef || !cover.previewRef) throw new Error("A completed final cover and preview are required.");
  const refs: Array<{ path: string; key: string; uploadReady: boolean; required: boolean }> = [{ path: "upload-ready/interior.pdf", key: String(interior.interiorRef), uploadReady: true, required: true }, { path: "upload-ready/cover-full-wrap.pdf", key: String(cover.coverRef), uploadReady: true, required: true }, { path: "preview-reference/cover-preview-with-guides.pdf", key: String(cover.previewRef), uploadReady: false, required: true }, { path: "validation/validation-report.pdf", key: String(validation.reportPdf), uploadReady: false, required: true }];
  const sourceIds = input.approvedSourceImageIds ?? [];
  for (const assetId of sourceIds) { const asset = db.prepare(`SELECT storage_reference AS storageReference, status FROM generated_assets WHERE user_id = ? AND project_id = ? AND id = ? UNION ALL SELECT storage_key AS storageReference, status FROM reference_assets WHERE user_id = ? AND project_id = ? AND id = ? AND status = 'active' LIMIT 1`).get(userId, input.projectId, assetId, userId, input.projectId, assetId) as Record<string, unknown> | undefined; if (!asset || (asset.status !== "approved" && asset.status !== "active")) throw new Error(`Approved source image ${assetId} is unavailable.`); refs.push({ path: `approved-source-images/${assetId}`, key: String(asset.storageReference), uploadReady: false, required: false }); }
  const provenance = { manifestVersion: "export-provenance-v1", projectId: input.projectId, frozenProjectVersion: input.frozenProjectVersion, prompts: db.prepare(`SELECT id, page_plan_id AS pagePlanId, version, generation_model AS model, generation_endpoint AS endpoint, seed, content_hash_sha256 AS contentHash FROM prompt_versions WHERE user_id = ? AND project_id = ? ORDER BY page_plan_id, version`).all(userId, input.projectId), assets: db.prepare(`SELECT id, page_plan_id AS pagePlanId, prompt_version_id AS promptVersionId, generation_job_id AS generationJobId, ai_provenance_classification AS provenance, status, checksum_sha256 AS checksum, updated_at AS version FROM generated_assets WHERE user_id = ? AND project_id = ? ORDER BY created_at`).all(userId, input.projectId) };
  const readme = `# KDP Kids Book Studio Export\n\nFrozen project version: ${input.frozenProjectVersion}\n\n## Upload-ready\n\n- upload-ready/interior.pdf — final interior PDF.\n- upload-ready/cover-full-wrap.pdf — final no-guides full-wrap cover PDF.\n\n## Preview/reference-only\n\n- preview-reference/cover-preview-with-guides.pdf — annotated preview; do not upload.\n- approved-source-images/ — approved source images retained for provenance; do not upload as a package substitute.\n- validation/validation-report.pdf — readable preflight report.\n- provenance/provenance-manifest.json — prompt/model/seed/asset trace.\n- listing/listing-metadata.json and listing/listing-metadata.csv — listing reference metadata.\n\nThis package is ready for manual KDP upload review only when the validation report has no blocking findings. It does not submit to KDP or guarantee acceptance. Use KDP Print Previewer and complete KDP review before upload.\n`;
  const metadataJson = `${JSON.stringify(input.listingMetadata, null, 2)}\n`; const exportId = crypto.randomUUID(); const base = `${userId}/projects/${input.projectId}/exports/${exportId}`; const manifestRef = `${base}/export-manifest.json`; const jsonRef = `${base}/listing-metadata.json`; const csvRef = `${base}/listing-metadata.csv`; const readmeRef = `${base}/README.md`; const zipRef = `${base}/kdp-paperback-package.zip`; const artifactRecords: ExportArtifact[] = [];
  for (const ref of refs) { const digest = await streamHash(storage, ref.key); artifactRecords.push({ path: ref.path, storageReference: ref.key, sha256: digest.sha256, required: ref.required, uploadReady: ref.uploadReady }); }
  const manifest = { manifestVersion: "export-package-v1", exportPackageId: exportId, projectId: input.projectId, frozenProjectVersion: input.frozenProjectVersion, validationRunId: input.validationRunId, generatedAt: new Date().toISOString(), artifacts: artifactRecords, provenance, listingMetadata: input.listingMetadata };
  await storage.put(jsonRef, Buffer.from(metadataJson), "application/json"); await storage.put(csvRef, Buffer.from(listingCsv(input.listingMetadata)), "text/csv"); await storage.put(readmeRef, Buffer.from(readme), "text/markdown"); await storage.put(manifestRef, Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`), "application/json");
  if (!storage.putStream) throw new Error("Configured private storage does not support streaming archive writes."); const archive = new archiver.ZipArchive({ zlib: { level: 6 } }); const output = new PassThrough(); const storePromise = storage.putStream(zipRef, output, "application/zip"); archive.pipe(output); for (const ref of refs) archive.append(streamFor(storage, ref.key), { name: ref.path }); archive.append(Buffer.from(metadataJson), { name: "listing/listing-metadata.json" }); archive.append(Buffer.from(listingCsv(input.listingMetadata)), { name: "listing/listing-metadata.csv" }); archive.append(Buffer.from(readme), { name: "README.md" }); archive.append(Buffer.from(`${JSON.stringify(provenance, null, 2)}\n`), { name: "provenance/provenance-manifest.json" }); archive.append(Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`), { name: "export-manifest.json" }); await Promise.all([archive.finalize(), storePromise]);
  const expiresAt = new Date(Date.now() + (input.retentionDays ?? 30) * 86400_000).toISOString(); db.prepare(`INSERT INTO export_packages (id, user_id, project_id, validation_run_id, kdp_preflight_run_id, package_kind, interior_storage_reference, cover_storage_reference, manifest_storage_reference, zip_storage_reference, status, frozen_project_version, artifact_hashes_json, listing_metadata_storage_reference, readme_storage_reference, cover_preview_storage_reference, final_confirmation_at, expires_at, retention_status, created_at, updated_at) VALUES (?, ?, ?, NULL, ?, 'zip', ?, ?, ?, ?, 'completed', ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?)`).run(exportId, userId, input.projectId, input.validationRunId, String(interior.interiorRef), String(cover.coverRef), manifestRef, zipRef, input.frozenProjectVersion, JSON.stringify(Object.fromEntries(artifactRecords.map((item) => [item.path, item.sha256]))), jsonRef, readmeRef, String(cover.previewRef), new Date().toISOString(), expiresAt, new Date().toISOString(), new Date().toISOString());
  return { exportPackageId: exportId, frozenProjectVersion: input.frozenProjectVersion, status: "completed", zipAccessUrl: await storage.createAccessUrl(zipRef, 900), artifacts: artifactRecords, expiresAt };
}

export function computeFrozenProjectVersion(projectUpdatedAt: string, input: Pick<FinalExportInput, "validationRunId" | "interiorExportRunId" | "coverExportRunId">): string { return frozenVersion(projectUpdatedAt, input); }
