import { useEffect, useRef } from "react";
import { AlertTriangle, X } from "lucide-react";

type Props = { open: boolean; title: string; description: string; confirmLabel: string; tone?: "danger" | "warning"; onConfirm: () => void; onCancel: () => void };
export default function ConfirmDialog({ open, title, description, confirmLabel, tone = "danger", onConfirm, onCancel }: Props) {
  const cancelRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (open) cancelRef.current?.focus(); }, [open]);
  useEffect(() => { if (!open) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onCancel(); }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [open, onCancel]);
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(32,51,72,.42)] p-5" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onCancel(); }}><section role="alertdialog" aria-modal="true" aria-labelledby="confirm-dialog-title" aria-describedby="confirm-dialog-description" className="w-full max-w-md rounded-3xl border border-[var(--line)] bg-[var(--paper-strong)] p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${tone === "danger" ? "bg-[#fff0ec] text-[#a54a3b]" : "bg-[#fff4dc] text-[#996d25]"}`}><AlertTriangle size={21} aria-hidden="true" /></div><button type="button" aria-label="Close confirmation dialog" onClick={onCancel} className="rounded-lg p-2 text-[var(--muted-ink)] hover:bg-[#eeeae0]"><X size={17} aria-hidden="true" /></button></div><h2 id="confirm-dialog-title" className="serif mt-5 text-2xl text-[var(--ink)]">{title}</h2><p id="confirm-dialog-description" className="mt-3 text-sm leading-6 text-[var(--muted-ink)]">{description}</p><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" ref={cancelRef} onClick={onCancel} className="rounded-full border border-[var(--line)] px-4 py-2.5 text-sm font-semibold text-[var(--ink)]">Keep it</button><button type="button" onClick={onConfirm} className={`rounded-full px-4 py-2.5 text-sm font-semibold text-white ${tone === "danger" ? "bg-[#a54a3b]" : "bg-[#996d25]"}`}>{confirmLabel}</button></div></section></div>;
}
